### ISSUE TITLE
Error while gettint metadata due to Python configparser bug

### ISSUE THREAD

**Issue by mdouchin** [3liz/qgis-atlasprint#16]
Quick report : the plugin fails to load with error `TypeError: 'PosixPath' object is not iterable` when reading the metadata.txt file.

Environment : Python 3.5.3 in Debian 9.11

Quick solution: replace
`config.read(metadata_file)`
with
`config.read(str(metadata_file))`
Found here: https://realpython.com/python-pathlib/

**Comment by Gustry** [comment]
I tried this code before, it was working well.
But I'm indeed running Python 3.7.

Sorry for that

**Comment by Gustry** [comment]
https://github.com/3liz/qgis-atlasprint/commit/1c2946306524c47eec9aa22b98d378547ab15648
