### ISSUE TITLE
Check $id for performance since QGIS 3 is used

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-atlasprint#23]
Related commit:
https://github.com/3liz/qgis-atlasprint/commit/ce911cf4893c0f978f978b17c65d3d4fa1e5090e
and
https://github.com/3liz/qgis-atlasprint/commit/99130fbfc51de8cea4e53cfae9837e8c7bd308d1

https://github.com/3liz/qgis-atlasprint/tree/qgis2

Check $id for performance since QGIS 3 is used

Maybe since 3.4, it's working without this hack. Needs to check with a big dataset.

**Comment by mdouchin** [comment]
Example of big dataset : parcelle layer from https://cadastre.data.gouv.fr/data/etalab-cadastre/2019-10-01/shp/departements/34/

**Comment by rldhont** [comment]
I confirm that $id could not be used for big dataset. $id has to be replaced by primaryKeys.
