### ISSUE TITLE
Difference between this plugin and native atlas capability in GetPrint

### ISSUE THREAD

**Issue by andreasneumann** [3liz/qgis-atlasprint#26]
Hi,

Thanks for sharing this plugin.

I am wondering what the difference between this plugin and the native atlas printing capability in QGIS server is?

Are you aware that QGIS server can already output an atlas as PDF?

You can provide an ATLAS_PK parameter with a filter: https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/services.html#atlas-pk

Or is this plugin meant to be used in older QGIS server instances that do not yet support atlas printing natively?

Thanks for the clarifications,
Andreas

**Comment by rldhont** [comment]
@andreasneumann we are aware of this, but ATLAS_PK is available since 3.8.

The plugin has been created for QGIS 2.14, has been port to QGIS 3.

We will also add features not supported by QGIS Server.

**Comment by andreasneumann** [comment]
Yes - what I thought.

Of course I encourage you to enhance native QGIS capabilities, but I understand there are reasons for the plugin version well.

We can close this issue of course. I was just wondering if you might not be aware about the native capabilities.
