### ISSUE TITLE
Is QGIS 2 supported?

### ISSUE THREAD

**Issue by AMDG2** [3liz/qgis-atlasprint#38]
Hello, it is not clear if QGIS2 is supported in latest plugin version?

Can you specify which versions are compatible with QGIS2 in the README?

**Comment by rldhont** [comment]
You can use [version 1.1.0](https://github.com/3liz/qgis-atlasprint/releases/tag/v1.1.0)

But QGIS 2 is not maintained since 2 years. It is recommended to update to QGIS 3.

**Comment by AMDG2** [comment]
Ok, thank for the feedback, do you have any recommendation to get QGIS on Ubuntu 18.04 ? (current Ubuntu LTS)

**Comment by Gustry** [comment]
I think you should follow qgis.org website to install QGIS.
