### ISSUE TITLE
Replace $id if it is numeric not only int

### ISSUE THREAD

**Issue by rldhont** [3liz/qgis-atlasprint#44]
The plugin only replace $id bay the corresponding field if it is an Int. https://github.com/3liz/qgis-atlasprint/blob/master/atlasprint/core.py#L249

QGIS Server is able to use numeric field as feature id.

So to fix some issue in generated atlas, it will be good to use
```py
if not field.isNumeric():
    return expression
```

**Comment by Gustry** [comment]
Done in 8bcc09b with test case
