### ISSUE TITLE
Set file permissions to 644

### ISSUE THREAD

**Issue by pcav** [3liz/qgis-atlasprint#45]
Currently unzipping the plugin results in files having 600 permission, and obviously the plugin does not work out of the box. Better if before unzipping file permissions are set to 644.

**Comment by Gustry** [comment]
Are you sure you don't need `744` or `755` ?.
Indeed, good idea

**Comment by pcav** [comment]
I think 644 is OK. In my case at least (Deb stable) it works.
Thanks for considering this.

**Comment by Gustry** [comment]
Done on Lizmap plugin server side in the latest version.
I will do that on other QGIS Server plugins : AtlasPrint, WfsOutputExtension etc

**Comment by pcav** [comment]
Thanks!

**Comment by Gustry** [comment]
Done as well in the next version of WfsOutputExtension

**Comment by Gustry** [comment]
Done for AtlasPrint : 75b6b13

**Comment by Gustry** [comment]
Related ticket : https://github.com/opengisch/qgis-plugin-ci/issues/99
