### ISSUE TITLE
Images in report are not displayed

### ISSUE THREAD

**Issue by arno974** [3liz/qgis-atlasprint#46]
We would like to add images in a report. While the attributes are displayed correctly, this is not the case for the image. The PDF report has to be refresh (F5) several times to display the image. Maybe is it because the PDF is generated faster than the time required to include the image ?

**Comment by Gustry** [comment]
@rldhont made some tweaks in the QGIS Server code about fetching images to make it async when rendering GetMap.

But I'm not sure how it is in the Atlas/Report print. https://qgis.org/api/classQgsLayoutExporter.html

**Comment by Gustry** [comment]
@arno974 Can you report us the version of QGIS Server ?

**Comment by arno974** [comment]
It is a 3Liz hosting service. Not sure which QGIS version it is.

**Comment by Gustry** [comment]
Is this issue still valid ?
Can you try again with an up to date version of QGIS Server ?

Your QGIS Server version is written in your plugin first tab, or in your Lizmap Web Client administration panel.

**Comment by arno974** [comment]
Sorry I didn't answer to your request about the version. Shame...
