### ISSUE TITLE
How to specify filter in a URL

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/qgis-atlasprint#5]
I have tried to add the filter in the URL like `&EXP_FILTER=TILE_NAME = '2625BC_11'` but without success.

What is the correct way to specify this.

An example of a full URL I have is 

http://localhost:8080/ows/?MAP=project.gqs
&SERVICE=WMS
&VERSION=1.3.0
&REQUEST=getprintatlas
&CRS=EPSG:3857
&FORMAT=pdf
&map0:EXTENT=2843457.452208557,-3051366.1691442365,2844680.4446611195,-3050143.1766916737
&map0:LAYERS=index
&map0:OPACITIES=125
&TEMPLATE=map
&DPI=150
&EXP_FILTER=TILE_NAME = '2625BC_11'

**Comment by pablodr81** [comment]
I also do not understand how filters are specified in the url.
I set the fid field of atlas layer as expression filter, so putting the following parameters, 

> ...&EXP_FILTER=67 

I get the following error on the screen.

> {"status" : "fail", "message": "ATLAS - Error while generating the PDF" }

And into qgisserver error file I get the next, after list all parameters, finish with this error:

` <ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc"> 
       <ServiceException code="OperationNotSupported">Request GetPrintAtlas is not supported</ServiceException>
</ServiceExceptionReport>

Atlas - No PDF generated in None`

**Comment by marioba** [comment]
I managed to make it work by escaping the `=` with the escape code `%3D`, for example to print the atlas for `fid=12`, I use:

`...&EXP_FILTER=fid%3D12`

**Comment by Gustry** [comment]
I'm adding it in the doc.

**Comment by mbernasocchi** [comment]
the better way to do this is to put the filter in quotes

`...&EXP_FILTER="fid=2"`
