### ISSUE TITLE
@lizmap_user still  not displayed despite v3.3.0

### ISSUE THREAD

**Issue by arno974** [3liz/qgis-atlasprint#54]
Even after updating atlasprint to 3.3.0, the lizmap_user variable is not interprated in atlas.
Exemple : 

Texte area in my print composer with atlas enabled 
`[%'Carte générée le : '  ||  format_date( now(), 'dd/MM/yyyy' ) || ' par ' ||  coalesce( @lizmap_user, 'utilisateur')%]`

Result : 
![image](https://user-images.githubusercontent.com/425243/156711898-8ed355f0-68c1-4496-914d-63fa26f199a5.png)

```
qgis-plugin-manager list
[sudo] password for arnaudvandecasteele: 
QGIS server version 3.16.4
List all plugins in /srv/qgis/plugins

--------------------------------------------------------------------------------------
|  Name    |  Version  |  Experimental  |  QGIS min  |  QGIS max  |  Author  |  Action ⚠    |
--------------------------------------------------------------------------------------
|atlasprint|3.3.0      |                |3.10        |            |3Liz      |              |
|Lizmap    |3.7.4      |                |3.4         |3.99        |3Liz      |Unkown version|
--------------------------------------------------------------------------------------
```

**Comment by Gustry** [comment]
I tried yesterday, it worked.
Can you send the HTTP request ? (in your developer tool when you click on the button).

Quick hint : `pip install qgis-plugin-manager --upgrade`, you are running an old version ;-)
